// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLlSJdXKPY2pgoNgy132yOK2Hb89Q2U-k',
    appId: '1:287537178636:web:a3dfb9e80d470504766629',
    messagingSenderId: '287537178636',
    projectId: 'multibob-9ca5c',
    authDomain: 'multibob-9ca5c.firebaseapp.com',
    storageBucket: 'multibob-9ca5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsNUmgVh51lt3y-okDWVTYg5hsRzOzCMQ',
    appId: '1:287537178636:android:cb833f35acc0db05766629',
    messagingSenderId: '287537178636',
    projectId: 'multibob-9ca5c',
    storageBucket: 'multibob-9ca5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7wf_tijwcfjReVPYutbs50MuwevN7IZ4',
    appId: '1:287537178636:ios:bab2756b3afe2f10766629',
    messagingSenderId: '287537178636',
    projectId: 'multibob-9ca5c',
    storageBucket: 'multibob-9ca5c.appspot.com',
    iosClientId: '287537178636-69fkbcjj8k87bc9e6t7iqscko4gbu7rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.skilledBobAppWeb',
  );
}
