// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmAzhMuXkTHvQoBwH9FhVX0sU1ebITe44',
    appId: '1:433553365514:web:ae3ea98e0854917bea5df3',
    messagingSenderId: '433553365514',
    projectId: 'multibob-808c1',
    authDomain: 'multibob-808c1.firebaseapp.com',
    storageBucket: 'multibob-808c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhDiPClAmLNs2zmyHUi5gsbS7VndIKqY',
    appId: '1:433553365514:android:dd148ac6deb4810eea5df3',
    messagingSenderId: '433553365514',
    projectId: 'multibob-808c1',
    storageBucket: 'multibob-808c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc90esRErifLI2EUnVWfpN3Fec-9hPPos',
    appId: '1:433553365514:ios:e08fd04aa2d77d8dea5df3',
    messagingSenderId: '433553365514',
    projectId: 'multibob-808c1',
    storageBucket: 'multibob-808c1.appspot.com',
    iosClientId: '433553365514-4v3hkomt827fjp3rcmrm38jfo2stio1f.apps.googleusercontent.com',
    iosBundleId: 'com.example.skilledBobAppWeb',
  );
}
